# Generated by Django 2.2.7 on 2020-09-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('image_name', models.CharField(max_length=20)),
                ('content_text', models.CharField(max_length=10000)),
                ('link', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
