# Generated by Django 2.2.7 on 2020-09-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cis_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_data',
            name='link',
        ),
    ]
